### ISSUE TITLE
cvmfspartsize fact should be an Integer

### ISSUE THREAD

**Issue by XMol** [voxpupuli/puppet-cvmfs#131]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.22
- Facter: 3.11.14
- Distribution: Scientific Linux 7.9
- Module version: 7.3.0

## What are you seeing

Warnings logged by the puppetserver process, e.g.

> 2021-03-24 00:04:33,855 WARN  [qtp868931630-68188] [puppetserver] Puppet The string '98204' was automatically coerced to the numerical value 98204 (file: /etc/puppetlabs/code/environments/production/modules/cvmfs/manifests/config.pp, line: 36, column: 75)

## What behaviour did you expect instead

No warnings.

## Any additional information you'd like to impart

Just cast to integer when the final number is found in [the fact](https://github.com/voxpupuli/puppet-cvmfs/blob/v7.3.0/lib/facter/cvmfspartsize.rb#L13).

```
Facter::Util::Resolution.exec("/bin/df -m -P #{directory}").split("\n").last.split(%r{\s+})[1].to_i
```

**Comment by traylenator** [comment]
Makes sense.
