### ISSUE TITLE
baseurl breaks usage for users with their own mirrors

### ISSUE THREAD

**Issue by mrolli** [voxpupuli/puppet-cvmfs#135]
https://github.com/voxpupuli/puppet-cvmfs/blob/315a15ea25086182ec4c8115393eab7229d77daf/manifests/yum.pp#L31

The new yumrepo baseurl build-up as it is now in 8.0.0 breaks the way we used the module so far:

```
cvmfs::cvmfs_quota_limit: 30000
cvmfs::cvmfs_cache_base: '/scratch/local/cvmfs/cache'
cvmfs::cvmfs_yum: "%{hiera('ubelix::mirror01')}/mrepo/centos%{facts.os.release.major}-$basearch/RPMS.cvmfs
                   %{hiera('ubelix::mirror02')}/mrepo/centos%{facts.os.release.major}-$basearch/RPMS.cvmfs"
cvmfs::cvmfs_http_proxy: 'http://cvmfs01.lhep.unibe.ch:3128|http://cvmfs02.lhep.unibe.ch:3128;http://proxy.arnes.si:3128;http://dcache.ijs.si:3128'
cvmfs::cvmfs_hash:
  atlas.cern.ch: {}
  atlas-condb.cern.ch: {}
  atlas-nightlies.cern.ch: {}
  sft.cern.ch: {}
  grid.cern.ch: {}
```

As the above hiera config shows, we use our own mirror due in order to be good citizens and not DDosing the cern server with our HPC cluster. We have to mirror and use the "load-balancing feautre" of yum using baseurl with two URLs. The new baseurl setup is breaking this.

Feature Request_
As a sysadmin I'd like to use my own URL (even two as above) without the module adding additional path segments to it.

If ok for you, Steve, I'm happy to provide a PR with the needed changes and unit tests in about two weeks, when I will have time for that. Any input on the form of the change you like to see?
I'd like to do something like @ghoneycutt is doing in his ghoneycutt/puppet-module-ssh - using 'USE_DEFAULTS' as the default value and acting with an if later to gather the real baseurl either by taking the user input as is or by generating the string as it is done now - for each of the three repos (though we do not need cvmfs-testing and cvmfs-config).
Or would you rather favor a solution like it is done in puppet-epel?

**Comment by traylenator** [comment]
https://github.com/voxpupuli/puppet-cvmfs/blob/master/manifests/init.pp#L105

what about just accepting an array of URLs in repo_base parameter ?

Looking at the ghoneycutt solution.

**Comment by mrolli** [comment]
Accepting an array of Stdlib::Httpurl instead of String with two URLs is the proper way of accepting the input, but is not the primary problem I'd like to solve here - sorry for the confusion. Maybe I should rephrase the request:

As a user I'd like to provide the final URL to our local repo (or URLs in our case) and not only the repo_base that gets additionally mangled in cmvfs:yum by appending OS major release and arch.

Thinking about that, I'd be better suggest to additionally present a repo_url parameter, which is used if provided, something like:

```
if $repo_url {
  baseurl = $repo_url,
} else {
  baseurl = "${repo_base}/cvmfs/EL/${facts['os']['release']['major']}/${facts['os']['architecture']}"
}

yumrepo {
  baseurl => $baseurl,
  ...
}
```

**Comment by traylenator** [comment]
That 2nd option less good as at the moment we profit that these URLs prefixes are the prefixes for debian as well.

**Comment by mrolli** [comment]
Ok, I think about it. Maybe the second one is still possible when having the base vor debian and RHEL and then adding more to the URL in OS-specific hiera files. I'll look into it and provide a PR upon which we can discuss further if that's ok for you.

**Comment by traylenator** [comment]
Given that by changing the path in your mirror it is not a mirror :smile: then I be tempted to say just set 

```
cvmfs::repo_manage: false
```
and add the repos yourself ?

**Comment by mrolli** [comment]
That would be the other "solution" that I almost started to implement. But then remembered that providing own URLs is possible for puppet-epel too then why not do it here to. But yes, providing my own yumrepo resource prior declaring cvmfs and then setting repo_manage to false would be absolutely a viable solution too.

Mirror in terms of content, not in terms of URL. We are doing mirrors using mrepo (setting it up with voxpupuli/puppet-mrepo) and that's how it works in the end. URLs in the form OS$major-$arch/RPMS.$reponame.

**Comment by mrolli** [comment]
Time is running... June already. I still owe you an answer. After seriously consulting the pillow I come to the same conclusion as you and we'll go the `cmvfs::repo_manage: false`-road and manage the `yumrepo` resource ourselves. Nevertheless, thanks for your time.
