### ISSUE TITLE
Update stdlib required version

### ISSUE THREAD

**Issue by XMol** [voxpupuli/puppet-cvmfs#149]
- Puppet: any
- Ruby: any
- Distribution: any
- Module version: 8.0.0

## How to reproduce (e.g Puppet code you use)
```puppet
include cvmfs
```

## What are you seeing
> Error: Resource type not found: Stdlib::Yes_no (file: /etc/puppetlabs/code/environments/puppet6/modules/cvmfs/templates/repo.local.epp, line: 10, column: 12) on node alice-sl7b-kit.gridka.de

## What behaviour did you expect instead
No error.

## Any additional information you'd like to impart
The requirements for module version 8.0.0 are inaccurate: In order to be able to use the `Stdlib::Yes_no` data type the version of the stdlib module must be [at least 6.1.0](https://github.com/puppetlabs/puppetlabs-stdlib/commit/a7c97905e345d5531a1d97d9361c6287ce35243a), not `">=4.13.1 < 7.0.0"` as written in [`metadata.json`](https://github.com/voxpupuli/puppet-cvmfs/blob/v8.0.0/metadata.json#L23).

**Comment by smortex** [comment]
Have you considered opening a Pull Request (PR) to add your change :wink:? This look like a perfect enhancement for a first-time contributor!

If you do not know how to start, here is a quite complete guide about the process of contributing to projects on GitHub:
https://dataschool.io/how-to-contribute-on-github

In any case, do not feel scared: we are here to help!

**Comment by XMol** [comment]
Hi @smortex,

thank you for the encouragement. Even though I would know how to contribute, I won't in this case, because I'm lacking the resources to test whether this is the _only_ issue with `metadata.json`. Also, my experience with GitHub Actions is too little to introduce a validation workflow to this project.

Best regards,
Xavier.

**Comment by XMol** [comment]
Thank you, @traylenator!
